import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";
import {Button, Flex, Heading, useColorModeValue, VStack, HStack} from "@chakra-ui/react";
import Logo200 from '../../public/logo/logo200.png'

export default function Layout({children}) {
    const bgColor = useColorModeValue('mygray.500', 'gray.800');
    return (
        <div>
            <Head>
                <title>Build It</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Flex direction="column" minH="100vh" bgColor={bgColor} rowGap={"10"} justifyContent={"center"} alignItems={"center"}>
                <Image src={Logo200} alt={"Logo"}/>
                {children}
            </Flex>
        </div>
    );
}